dry-run: null
hookfiles: ""
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
reporter: ["html", "junit", "markdown"]
output: ["test_output/dredd_output.html", "test_output/dredd.xml", "test_output/dredd.md"]
header: ["apikey: b5a44b32ba2f42f8b27fcaf1bd86e813"]
sorted: false
user: null
inline-errors: false
details: false
method: ["GET", "PUT", "POST", "DELETE"]
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: "analysis/generated/open-api.apib"
endpoint: 'http://openapi.hcnet.vn:8000/openapi/v1/'
