FORMAT: 1A

:[Description](src/includes/description.apib)

## Group Security

:[Group API keys](src/includes/group-api-keys.apib)

 ___
 
:[Group Profile](src/includes/group-profile.apib)

:[Data Structures](src/includes/data-structures.apib)
